### PR TITLE
SAPCC OpenStack link fix

### PR DESCRIPTION
**Pull request by ScottBrenner**
Current link no longer exists, believe this is the new correct link.

### CODE REVIEW

**Comment by madorn** [comment]
@ScottBrenner Hi Scott: It looks like the OpenStack Operator is gone..should this be updated with [OpenStack Seeder Operator](https://github.com/sapcc/kubernetes-operators/tree/master/openstack-seeder)?

**Comment by ScottBrenner** [comment]
Should it? I'm not sure what any of these are, just noticed the current link no longer exists 😁

**Comment by madorn** [comment]
Thanks! I will update the link!

**Pull request closed without merging**
